"""
NumPy: meshgrid (with visualization)

- np.meshgrid(x, y) generates coordinate matrices for a grid.
- Useful in plotting surfaces or evaluating functions over 2D space.

Example: Creating a grid from x=[1,2,3], y=[4,5]
and showing it visually.
"""

import numpy as np
import matplotlib.pyplot as plt

# Define x and y values
x = np.array([1,2,3])
y = np.array([4,5])

# Create grid
X, Y = np.meshgrid(x, y)
print("X Grid:\n", X)
print("Y Grid:\n", Y)

# Example function: z = x^2 + y^2
Z = X**2 + Y**2

# Plot the grid points
plt.figure(figsize=(6,6))
plt.scatter(X, Y, c='red', s=100)
for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        plt.text(X[i,j]+0.1, Y[i,j], f"({X[i,j]},{Y[i,j]})")

plt.title("Points generated by meshgrid")
plt.xlabel("X")
plt.ylabel("Y")
plt.grid(True)
plt.show()
